# Generated by Django 3.2.7 on 2021-10-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='gift_cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.gift_cart'),
            preserve_default=False,
        ),
    ]
