# Generated by Django 3.2.7 on 2021-10-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cartproduct_gift_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='gift_cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
