# Generated by Django 3.2.7 on 2021-10-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211007_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti', 'پرداخت اینترنتی')], default='Cash On Delivery', max_length=20),
        ),
    ]
